CREATE DATABASE nhasach

USE nhasach 
GO

CREATE TABLE SACH(
	MASACH INT PRIMARY KEY IDENTITY,
	MANXB INT,
	TENSACH NVARCHAR(50),
	TACGIA NVARCHAR(50),
	THELOAI NVARCHAR(50),
	DONGIA SMALLMONEY
)

USE nhasach 
GO

CREATE TABLE NXB(
	MANXB INT PRIMARY KEY IDENTITY,
	TENNXB NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SDT VARCHAR(20)
)

USE nhasach 
GO

CREATE TABLE PHIEUNHAP(
	MAPN INT PRIMARY KEY IDENTITY,
	MANV INT,
	NGAYNHAP SMALLDATETIME,
	TONGCHI SMALLMONEY
)

USE nhasach 
GO

CREATE TABLE CTPHIEUNHAP(
	MAPN INT PRIMARY KEY IDENTITY,
	MASACH INT,
	SOLUONGNHAP INT,
	DONGIA SMALLMONEY,
	MANCC INT
)

USE nhasach 
GO

CREATE TABLE HOADON(
	MAHD INT PRIMARY KEY IDENTITY,
	MANV INT,
	MAKH INT,
	NGHD SMALLDATETIME,
	TRIGIA SMALLMONEY
)

USE nhasach 
GO

CREATE TABLE CTHD(
	MAHD INT,
	MASACH INT,
	SOLUONG INT,
	PRIMARY KEY(MAHD,MASACH)
)

USE nhasach 
GO

CREATE TABLE KHACHHANG (
	MAKH INT PRIMARY KEY IDENTITY,
	HOTEN NVARCHAR(50),
	SDT VARCHAR(20),
	EMAIL VARCHAR(50),
	NGAYSINH SMALLDATETIME,
	DIEMTICHLUY INT
)

USE nhasach 
GO

CREATE TABLE BAOCAODOANHTHU(
	ID INT PRIMARY KEY IDENTITY,
	NGAYLAP SMALLDATETIME,
	DOANHTHU INT
)

USE nhasach 
GO

CREATE TABLE CTBCDT(
	ID INT,
	MAHD INT,
	TRIGIA SMALLMONEY,
	PRIMARY KEY(ID,MAHD)
)

USE nhasach 
GO

CREATE TABLE PHIEUDAT(
	MAPD INT PRIMARY KEY IDENTITY,
	MANV INT,
	NGAYDAT SMALLDATETIME
)


CREATE TABLE CTPHIEUDAT(
	MAPD INT,
	MASACH INT,
	SOLUONG INT,
	MANCC INT,
	PRIMARY KEY(MAPD,MASACH)
)

USE nhasach 
GO

CREATE TABLE NHAVIEN(
	MANV INT PRIMARY KEY IDENTITY,
	HOTEN NVARCHAR(50),
	SDT VARCHAR(20),
	CMND VARCHAR(20),
	DIACHI NVARCHAR(50),
	NGAYSINH SMALLDATETIME,
	TAIKHOAN VARCHAR(20),
	MATKHAU VARBINARY(20)
)

USE nhasach 
GO

CREATE TABLE NCC(
	MANCC INT PRIMARY KEY IDENTITY,
	TENNCC NVARCHAR(50),
	EMAIL NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SDT VARCHAR(20)
)

USE nhasach 
GO

-- KHOA NGOAI BANG SACH
ALTER TABLE dbo.SACH ADD FOREIGN KEY (MANXB) REFERENCES dbo.NXB(MANXB);

-- KHOA NGOAI BANG PHIEUNHAP
ALTER TABLE dbo.PHIEUNHAP ADD FOREIGN KEY (MANV) REFERENCES dbo.NHAVIEN(MANV);

--CTPHIEUNHAP

ALTER TABLE dbo.CTPHIEUNHAP ADD FOREIGN KEY (MAPN) REFERENCES dbo.PHIEUNHAP(MAPN);
ALTER TABLE dbo.CTPHIEUNHAP ADD FOREIGN KEY (MASACH) REFERENCES dbo.SACH(MASACH);
ALTER TABLE dbo.CTPHIEUNHAP ADD FOREIGN KEY (MANCC) REFERENCES dbo.NCC(MANCC);

-- CTHD
ALTER TABLE dbo.CTHD ADD FOREIGN KEY(MAHD) REFERENCES dbo.HOADON(MAHD);
ALTER TABLE dbo.CTHD ADD FOREIGN KEY (MASACH) REFERENCES dbo.SACH(MASACH);

-- HOADON
ALTER TABLE dbo.HOADON ADD FOREIGN KEY(MANV) REFERENCES dbo.NHAVIEN(MANV);
ALTER TABLE dbo.HOADON ADD FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH);

-- CTBCDT

ALTER TABLE dbo.CTBCDT ADD FOREIGN KEY (MAHD) REFERENCES dbo.HOADON(MAHD);
ALTER TABLE dbo.CTBCDT ADD FOREIGN KEY (ID) REFERENCES dbo.BAOCAODOANHTHU(ID);

-- PHIEUDAT
ALTER TABLE dbo.PHIEUDAT ADD FOREIGN KEY (MANV) REFERENCES dbo.NHAVIEN(MANV);

-- CTPHIEUDAT
ALTER TABLE dbo.CTPHIEUDAT ADD FOREIGN KEY (MAPD) REFERENCES dbo.PHIEUDAT(MAPD);
ALTER TABLE dbo.CTPHIEUDAT ADD FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH);
ALTER TABLE dbo.CTPHIEUDAT ADD FOREIGN KEY(MANCC) REFERENCES dbo.NCC(MANCC);

--


--DROP DATABASE nhasach